### ISSUE TITLE
Error Adding rule

### ISSUE THREAD

**Issue by powermx** [HirbodBehnam/V2Ray-Installer#1]
jq: error (at /usr/local/etc/v2ray/config.json:1): Cannot iterate over null (null)

**Comment by HirbodBehnam** [comment]
Hello
Can you provide more information? Where this happens? What is the content of config file? And what did you do before it?

**Comment by powermx** [comment]
> Hello Can you provide more information? Where this happens? What is the content of config file? And what did you do before it?

What do you want to do?
        1) Add rule
        2) Edit VMess/VLess/Trojan accounts
        3) Generate client config
        4) Delete rule
        5) Uninstall v2fly
        *) Exit
Please enter an option: 1
Select a port to proxy listen on it: 443
jq: error (at /usr/local/etc/v2ray/config.json:1): Cannot iterate over null (null)
On what interface you want to listen?: 0.0.0.0

**Comment by HirbodBehnam** [comment]
And what is in your config file?
Config file is located at `/usr/local/etc/v2ray/config.json`

**Comment by powermx** [comment]
It's empty

**Comment by HirbodBehnam** [comment]
Do you remember what did you did that you ended up with an empty config?
Looks like script does produce a bug in some case which writes empty config. If you want to fix it and continue using script I suggest you to run the following command:
```bash
echo '{"log":{"loglevel":"warning","access":"none"},"inbounds":[],"outbounds":[{"protocol":"freedom"}]}' > /usr/local/etc/v2ray/config.json
```

**Comment by HirbodBehnam** [comment]
As I said, I cannot reproduce it. If you found a consistent way to reproduce it please leave a comment.
