### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by Saeid008** [HirbodBehnam/V2Ray-Installer#2]
سلام. 
آیا راهی وجود داره که روی لینوکس روی یه پورت مشخص تعداد کانکشن های متصل رو روی یه عدد خاص لیمیت کنیم؟ یا حتی روی ویندوز سرور اگر همچنین راهی وجود داشته باشه ممنون میشم راهنمایی کنید؟

**Comment by HirbodBehnam** [comment]
سلام نه تا جایی که می دونم ممکن نیست

**Comment by nDman** [comment]
اسکریپت [DDoS Deflate](https://github.com/jgmdev/ddos-deflate) رو نصب کنید. میتونید تعداد کانکشن هر آی پی رو محدود کنید که اگر بیشتر کانکت شد اون آی پی رو بن کنه. و حتی میتونین سرعت کانکشن رو محدود کنید.
